### ISSUE TITLE
Wallet Installation

### ISSUE THREAD

**Issue by C0inPr0fit** [procurrency/procurrency#1]
I'm trying to install the wallet on my Linux system but I don't know how to. I downloaded and unpacked both packages. Are there install instructions for the "non expert Linux users"? I'm on Ubuntu 16.04. Please help. Thank you.

**Comment by rkanadev** [comment]
If you are on Linux 16.04, please compile the wallet yourself using qt for
linux.
The Wallet is only compatible for Linux 14.04 64bit and use boost v1.5.4

**Comment by C0inPr0fit** [comment]
Use boost v1.5.4?

**Comment by C0inPr0fit** [comment]
I don't know how to compile my own binaries yet. I had to install Linux to
make a hand me down comp usable. I am lost here.

**Comment by ProCoinDEV** [comment]
You can't launch it on ubuntu 16.04 unless you compile the wallet yourself.
You need to install all the apt-get as if you were going to launch to compile but you don't need to compile because it is already in the binary.

**Comment by C0inPr0fit** [comment]
I don't understand how to do that. Just enter "sudo apt-get ProCurrency-qt"?

**Comment by rkanadev** [comment]
Use these commands if you are on Ubuntu 14.04 x64 - as the current compiled
binary work on that version of ubuntu only

sudo apt-get update

sudo apt-get upgrade

sudo apt-get install build-essential libssl-dev libboost-all-dev git
libdb5.1++-dev libminiupnpc-dev screen

and then double click on ProCurrency-qt for linux to launch the wallet

**Comment by C0inPr0fit** [comment]
But I'm on 16.04. If it's not compatible with 16.04 I'm basically S.O.L.?

**Comment by C0inPr0fit** [comment]
Will the Dev Team be releasing an Android App for the PROC Wallet?

**Comment by CharlyBarley** [comment]
Hi rkanadev, i used those commands in ubuntu 14.04 and when i go to click on the ProCurrency-qt download i got from procommerce.io nothing happens, there was only one executable file i found when i extracted the download.  what would be the command to run the ProCurrency-qt? thanks, Charly

**Comment by rkanadev** [comment]
are you on ubuntu 14.04 x64?

**Comment by CharlyBarley** [comment]
i'm on ubuntu studio 14.04 x64, maybe it won't work on studio?

**Comment by CharlyBarley** [comment]
hello,
i finally got it to launch. i had to add kde libraries to get it to launch the qt cause ubuntu studio 14 doesn't have the qt support.  it looks like it is running now and synced and receiving and sending. it's been running for half a day, and i'm not seeing any transactions? how long until i will start seeing something? do i have to actually have some coins already to be able to stake and get more? how do i do that, get someone else to send me a few coins? thanks

**Comment by PROcommerce** [comment]
Great to see that it worked!
Depends on how many coins you have staking.
You can purchase some in exchanges.

**Comment by CharlyBarley** [comment]
thanks Rod,
i'm a member or ipro network, and i'm waiting for some of my coins to be made available. i left it running for a day, and i noticed that a receive address showed up, but now when i let it run there are no receive addresses showing. what do i have to do to get the receive address to show up again so i can send myself some proc to get started? thanks

**Comment by PROcommerce** [comment]
Hello,

All you have to do is exit the wallet, wait ten seconds and re-open the wallet.

Thank you.

**Comment by bncase** [comment]
I add sudo.... and get this, ben@ben-Aspire-6920:~$ sudo apt-get update
[sudo] password for ben: 
I can't type anything after ben: , I should be able to type my password but why not?

**Comment by banone79** [comment]
bncase, when you type in your password, nothing is displayed on the screen.  This is normal, just type in your root password and hit enter.

**Comment by CharlyBarley** [comment]
can someone please show me the commands to update pro wallet for Linux 14.04 64bit to PROC v1.3.5 , my wallet shows i'm using ProCurrency v1.1.0.0: Initial  thank you

**Comment by CharlyBarley** [comment]
i downloaded the tar.gz zip file for PROC v1.3.5  to my desktop, when i go to unzip it ProCurrency-qt, linux tells me there is already a file named ProCurrency-qt, and it asked if i want to replace it. if i answer yes, will it upgrade the software?  can someone please show me the process to update, thank you

**Comment by CharlyBarley** [comment]
can someone please show me the commands to update pro wallet for Linux
14.04 64bit to PROC v1.3.5 , my wallet shows i'm using ProCurrency
v1.1.0.0: Initial thank you

i downloaded the tar.gz zip file for PROC v1.3.5 to my desktop, when i go
to unzip it ProCurrency-qt, linux tells me there is already a file named
ProCurrency-qt, and it asked if i want to replace it. if i answer yes, will
it upgrade the software? can someone please show me the process to update,
thank you
