### ISSUE TITLE
How to Install Wallet on Windows 10

### ISSUE THREAD

**Issue by dj4926** [procurrency/procurrency#2]
Can you provide instruction on installing this wallet on Windows 10?

**Comment by rkanadev** [comment]
Just unpack the archive to your desire location and double on
"procurrency-qt.exe" to launch the wallet.
There is no installation setup needed for now but maybe in the future.

**Comment by dj4926** [comment]
Thanks.

**Comment by MillionDollarMind** [comment]
@rkanadev @PROcommerce I am desperately needing some help fixing some wallet issues. I have emailed in but nothing I have been told is working. Is there anyone that can call or work with me directly? I am getting a " OUT OF SYNC" message and it is saying that it has not downloaded 11686 blocks of data. I have restarted, deleted the files, reinstalled, nothing is working.... in fact, when I reinstall, it is somehow loading my coins, so somewhere I don't think I am deleting completely. There is no program in my uninstall list.... I have no clue how to fix. Can you please help?
![pro wallet failure](https://cloud.githubusercontent.com/assets/28722292/26089797/36f80fbc-39b5-11e7-8b9f-28aec0a2fc32.png)

**Comment by rkanadev** [comment]
What is your issue exactly?
There is no installation needed. Just launch procurrency-qt.exe and you are all set.
Your Wallet data is in "/Roaming/ProCurrency" There you need to backup your "wallet.dat" before deleting anything or you will easily lose your coins.

**Comment by MillionDollarMind** [comment]
The issue is that it is not syncing with the blockchain and douwnloading any blocks of data. As you can see in the picture above, it shows blocks of data sitting there. It will never download for some reason and give the "OUT OF SYNC" message in the top by my balance. I have sent all coins I had in there at this time out to someone I know to test and to preserve them. It is now showing 13106 blocks of data not synced as the image above is dated. I have tried everything from deleting all files I know of and reinstalling... still will not fix the problem. I have backed up the wallet with the remaining 0.99990000 coin left. It will however, bring all my coin back after deletion... like it was never wiped. I know this sounds pieced together... I just have been through this 100x with everyone that I know that might know how to fix along with your email support. The last email I sent in I never got a response. Can someone call me and I can walk them through?

**Comment by MillionDollarMind** [comment]
I am not totally positive how and when staking takes place, but from what I can tell, this is blocking the staking and maturing of coins. I can still send and I would assume receive coins.

**Comment by PROcommerce** [comment]
Hello,

What is the current hard drive space available on your PC?

**Comment by MillionDollarMind** [comment]
30.4 GB on my C: drive and 835 GB on my D: drive

**Comment by PROcommerce** [comment]
Has the blockchain caught up? Or is it still loading?

**Comment by MillionDollarMind** [comment]
No, It says 14,161 blocks remaining. Last received block was 15 days ago. Still loading....
From what I have heard from others, I am not the only one having issues.

**Comment by MillionDollarMind** [comment]
@rkanadev @PROcommerce Any other thoughts you can help me with? I seriously have exhausted my little knowledge.

**Comment by PROcommerce** [comment]
Hello,

Try the following steps;

1. Head to Help>Debug Window>Console> and type this command;
rewindchain 500
Exit the wallet, wait 10 second and re-open.

**Comment by PROcommerce** [comment]
If that doesnt work. These steps will reset your files;

1.Exit the Wallet then type into the “Cortana” search bar at the bottom left hand this command: (%appdata%) then hit enter.
2. Click on the “Roaming” folder.
3. Once the folder is opened, head to the “ProCurrency” folder.
4. Inside the Procurrency, delete every file in that folder except “wallet.dat” (Do not delete that file or you will loose your coins) Exit folders.
5. Open “ProCurrencyQT” wallet.
6. Coins should reappear when it is fully synced. (It’s about an hour as of July 2017)

**Comment by AMVill** [comment]
PLEASE HELP!!! It have been trying for days to fix the "OUT OF SYNC" - i went through all the steps and nothing is working!? Can I unistall it?

**Comment by PROcommerce** [comment]
Stuck BlockchainReset (Windows)



1. Exit the Wallet then type into the “Cortana” search bar at the bottom left hand corner. Type this command: (%appdata%) then hit enter.
2. Click on the “Roaming” folder.
3. Once the folder is opened, head to the “ProCurrency” folder.
4. Inside the Procurrency, delete every file in that folder except "wallet.dat” (DO NOT DELETE THAT FILE OR YOU WILL LOSE YOUR COINS!) Exit folders.
5. Open “ProCurrencyQT” wallet.
6. Coins should reappear when it is fully synced. (It’s about an hour as of July 2017)
